# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['app.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('Combined_Incidents_Report_Feb_to_June_2025.xlsx', '.'),
        ('templates', 'templates'),
        ('MTTR.py', '.'),
        ('Regions-Groups.xlsx', '.'),
        ('Pre-TSQ Data-FebTOJune2025.xlsx', '.'),
    ],
    hiddenimports=[
        'flask',
        'flask_cors',
        'pandas',
        'numpy',
        'openpyxl',
        'xlrd',
        'jinja2',
        'markupsafe',
        'itsdangerous',
        'werkzeug',
        'click',
        'blinker',
        'socket',
        'atexit',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'torch',
        'tensorboard',
        'tensorflow',
        'cv2',
        'matplotlib',
        'scipy',
        'sklearn',
        'seaborn',
        'plotly',
        'bokeh',
        'altair',
        'streamlit',
        'jupyter',
        'IPython',
        'notebook',
        'jupyterlab',
        'pytest',
        'unittest',
        'doctest',
        'tkinter',
        'PyQt5',
        'PyQt6',
        'PySide2',
        'PySide6',
        'wx',
        'kivy',
        'pygame',
        'PIL.ImageQt',
        'PyQt5.QtCore',
        'PyQt5.QtGui',
        'PyQt5.QtWidgets',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='MBR_Dashboard.exe',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
    version='version_info.txt',
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='MBR_Dashboard_Windows',
) 